#%RAML 1.0 DataType

properties:
  Disclaimer:
    displayName: The Disclaimer schema
    description: An explanation about the purpose of this instance.
    default: ''
    type: string
    required: false
  Source1:
    displayName: The Source1 schema
    description: An explanation about the purpose of this instance.
    default: ''
    type: string
    required: false
  Policies_NGA:
    displayName: The Policies_NGA schema
    description: An explanation about the purpose of this instance.
    type: object
    additionalProperties: true
    properties:
      Reported_Date_Time:
        displayName: The Reported_Date_Time schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Province_State_Code:
        displayName: The Province_State_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Province_State_Name:
        displayName: The Province_State_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Emergency_Declaration_Code:
        displayName: The Emergency_Declaration_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      National_Guard_Activation_Code:
        displayName: The National_Guard_Activation_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      State_Employee_Travel_Restriction_Code:
        displayName: The State_Employee_Travel_Restriction_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Gathering_Restriction_Code:
        displayName: The Gathering_Restriction_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      School_Closure_Code:
        displayName: The School_Closure_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Non_Essential_Business_Closure_Code:
        displayName: The Non_Essential_Business_Closure_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Non_Essential_Business_Closure_Partial_Code:
        displayName: The Non_Essential_Business_Closure_Partial_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Non_Essential_Business_Declaration_Code:
        displayName: The Non_Essential_Business_Declaration_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Statewide_Curfew_Code:
        displayName: The Statewide_Curfew_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Domestic_Travel_Restriction_Code:
        displayName: The Domestic_Travel_Restriction_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Face_Covering_Policy_Code:
        displayName: The Face_Covering_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Major_Disaster_Declaration_Code:
        displayName: The Major_Disaster_Declaration_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Reopening_Plan_Code:
        displayName: The Reopening_Plan_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Reopening_Plan_URL:
        displayName: The Reopening_Plan_URL schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Reopening_Task_Force_URL:
        displayName: The Reopening_Task_Force_URL schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
    required: false
  Source2:
    displayName: The Source2 schema
    description: An explanation about the purpose of this instance.
    default: ''
    type: string
    required: false
  Policies_UnivWashington:
    displayName: The Policies_UnivWashington schema
    description: An explanation about the purpose of this instance.
    type: object
    additionalProperties: true
    properties:
      Policy_Name:
        displayName: The Policy_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Report_Date:
        displayName: The Report_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Report_Release_Note_Text:
        displayName: The Report_Release_Note_Text schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Global_Burden_Disease_Identifier:
        displayName: The Global_Burden_Disease_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Province_State_Code:
        displayName: The Province_State_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Province_State_Name:
        displayName: The Province_State_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Province_State_FIPS_Number:
        displayName: The Province_State_FIPS_Number schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Mandatory_Code:
        displayName: The Policy_Mandatory_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Statewide_Geographic_Policy_Code:
        displayName: The Statewide_Geographic_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Statewide_Population_Policy_Code:
        displayName: The Statewide_Population_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Issue_Date:
        displayName: The Policy_Issue_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Enactment_Date:
        displayName: The Policy_Enactment_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Expiry_Date:
        displayName: The Policy_Expiry_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_End_Date:
        displayName: The Policy_End_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Extended_Identifier:
        displayName: The Policy_Extended_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Expanded_Identifier_:
        displayName: The Policy_Expanded_Identifier_ schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Eased_Identifier:
        displayName: The Policy_Eased_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Ended_Identifier:
        displayName: The Policy_Ended_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Depended_Identifier:
        displayName: The Policy_Depended_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Note_Text:
        displayName: The Policy_Note_Text schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Source_URL:
        displayName: The Policy_Source_URL schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Source_Identifier:
        displayName: The Policy_Source_Identifier schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      External_Record_Id:
        displayName: The External_Record_Id schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Primary_Data_Source_Name:
        displayName: The Primary_Data_Source_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Secondary_Data_Source_Name:
        displayName: The Secondary_Data_Source_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
    required: false

example: !include ../examples/detailedPolicyResponse.json