#%RAML 1.0 DataType

type: object
displayName: errorMessage

properties: 
  message:
    type: string
    required: true
    description: Error message to be shown to the user
    default: There was an error