#%RAML 1.0 DataType

properties:
  leftTopLatLong:
    type: number
    multipleOf: 0.000001
    minimum: -90
    maximum: 180
    required: false  
  rightTopLatLong:
    type: number
    multipleOf: 0.000001
    minimum: -90
    maximum: 180
    required: false
  leftBottomLatLong:
    type: number
    multipleOf: 0.000001
    minimum: -90
    maximum: 180
    required: false
  rightBottomLatLong:
    type: number
    multipleOf: 0.000001
    minimum: -90
    maximum: 180
    required: false