#%RAML 1.0 DataType

properties:
  Disclaimer:
    displayName: The Disclaimer schema
    description: An explanation about the purpose of this instance.
    default: ''
    type: string
    required: false
  Community_regulations:
    displayName: The Community_regulations schema
    description: An explanation about the purpose of this instance.
    type: object
    additionalProperties: true
    properties:
      Gathering_Restriction_Code:
        displayName: The Gathering_Restriction_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      School_Closure_Code:
        displayName: The School_Closure_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Non_Essential_Business_Closure_Code:
        displayName: The Non_Essential_Business_Closure_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Social_Distancing_Requirement_Code:
        displayName: The Social_Distancing_Requirement_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Face_Covering_Policy_Code:
        displayName: The Face_Covering_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Bar_Restrictions_Code:
        displayName: The Bar_Restrictions_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Reopening_Plan_Code:
        displayName: The Reopening_Plan_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Stay_at_Home_Requirement_Code:
        displayName: The Stay_at_Home_Requirement_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Domestic_Travel_Restrictions_Code:
        displayName: The Domestic_Travel_Restrictions_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Restaurant_Restrictions_Code:
        displayName: The Restaurant_Restrictions_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Report_Date:
        displayName: The Report_Date schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Country_Alpha_3_Code:
        displayName: The Country_Alpha_3_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Country_Short_Name:
        displayName: The Country_Short_Name schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Gathering_Restriction_Notes_:
        displayName: The Gathering_Restriction_Notes_ schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      School_Closure_Notes:
        displayName: The School_Closure_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Non_Essential_Business_Closure_Notes:
        displayName: The Non_Essential_Business_Closure_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Event_Cancellation_Code:
        displayName: The Public_Event_Cancellation_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Event_Cancellation_Notes_:
        displayName: The Public_Event_Cancellation_Notes_ schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Transport_Closure_Code:
        displayName: The Public_Transport_Closure_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Transport_Closure_Notes:
        displayName: The Public_Transport_Closure_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Stay_at_Home_Requirement_Notes:
        displayName: The Stay_at_Home_Requirement_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Domestic_Travel_Restrictions_Notes:
        displayName: The Domestic_Travel_Restrictions_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      International_Travel_Restrictions_Code:
        displayName: The International_Travel_Restrictions_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      International_Travel_Restrictions_Notes:
        displayName: The International_Travel_Restrictions_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Income_Support_Code:
        displayName: The Income_Support_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Income_Support_Notes:
        displayName: The Income_Support_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Debt_Contract_Relief_Code:
        displayName: The Debt_Contract_Relief_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Debt_Contract_Relief_Notes:
        displayName: The Debt_Contract_Relief_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Fiscal_Measures_Code:
        displayName: The Fiscal_Measures_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Fiscal_Measures_Notes:
        displayName: The Fiscal_Measures_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Fiscal_International_Policy_Code:
        displayName: The Fiscal_International_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Fiscal_International_Policy_Notes:
        displayName: The Fiscal_International_Policy_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Information_Campaigns_Code:
        displayName: The Public_Information_Campaigns_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Public_Information_Campaign_Notes:
        displayName: The Public_Information_Campaign_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Testing_Policy_Code:
        displayName: The Testing_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Testing_Policy_Notes:
        displayName: The Testing_Policy_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Contact_Tracing_Policy_Code:
        displayName: The Contact_Tracing_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Contact_Tracing_Policy_Notes_Txt:
        displayName: The Contact_Tracing_Policy_Notes_Txt schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Emergency_Investment_In_Healthcare_Code:
        displayName: The Emergency_Investment_In_Healthcare_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Emergency_InvestmentIn_Healthcare_Notes:
        displayName: The Emergency_InvestmentIn_Healthcare_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Investment_In_Vaccines_Code:
        displayName: The Investment_In_Vaccines_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Investment_In_Vaccines_Notes:
        displayName: The Investment_In_Vaccines_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Other_Policy_Code:
        displayName: The Other_Policy_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Other_Policy_Notes:
        displayName: The Other_Policy_Notes schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Policy_Stringency_Index_Code:
        displayName: The Policy_Stringency_Index_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Government_Response_Index_Code:
        displayName: The Government_Response_Index_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Containment_And_Health_Policy_Index_Code:
        displayName: The Containment_And_Health_Policy_Index_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
      Economic_Support_Policies_Index_Code:
        displayName: The Economic_Support_Policies_Index_Code schema
        description: An explanation about the purpose of this instance.
        default: ''
        type: string
        required: false
    required: false
  Source:
    displayName: The Source schema
    description: An explanation about the purpose of this instance.
    default: ''
    type: string
    required: false

example: !include ../examples/oxfordResponse.json