#%RAML 1.0 DataType

properties:
  zipCd:
    displayName: ZIP Code
    description: ZIP code
    type: string
    required: false
  geo:
    displayName: Geograpic Information
    description: Geographic Information in Decimal Degrees (WGS1984)
    type: !include geo-type.raml
    required: false
  counties:
    type: array
    items:
      properties:
        countyName:
          displayName: County
          description: Name of the current County
          type: string
          required: false
        reportedCt:
          displayName: Covid-19 Reported Count
          description: Number of people that have been reported with COVID-19
          type: number
          multipleOf: 1
          minimum: 0
          required: false
        deathCt:
          displayName: Covid-19 Death Count
          description: Number of people that have been reported dead from COVID-19 
          type: number
          multipleOf: 1
          minimum: 0
          required: false
        recoveredCt:
          displayName: Covid-19 Recovered Count
          description: Number of people that have recovered from COVID-19 
          type: number
          multipleOf: 1
          minimum: 0
          required: false
example: !include ../examples/zip-200-response.json
  